"""judgekit: evaluate your evaluators, with judge-vs-human validity as the headline metric."""

from judgekit.calibration import RaterRatings, execute_calibration, write_report
from judgekit.dataset import load_dataset, load_outputs, load_rater, load_ratings
from judgekit.errors import (
    BudgetExceededError,
    CalibrationError,
    DatasetError,
    JudgeError,
    JudgekitError,
    ProviderError,
    RunError,
    ScoringError,
    StatsError,
    UnknownScorerError,
)
from judgekit.judge import execute_judge, load_judge_config, write_judge_artifact
from judgekit.models import (
    AgreementEstimate,
    CalibrationReport,
    Case,
    CaseRecord,
    Dataset,
    JudgeConfig,
    JudgeConfigRecord,
    JudgeParams,
    JudgePricing,
    JudgeRunArtifact,
    JudgeRunManifest,
    JudgeTotals,
    JudgeVerdict,
    KappaEstimate,
    OutputRecord,
    RaterSummary,
    RatingRecord,
    RunArtifact,
    RunManifest,
    RunResult,
    RunSummary,
    SliceAgreement,
)
from judgekit.providers import (
    AnthropicProvider,
    OpenAICompatibleProvider,
    Provider,
    ProviderRequest,
    ProviderResponse,
    get_provider,
)
from judgekit.runner import execute_run, write_artifact
from judgekit.scorers import Scorer, available_scorers, get_scorer, register
from judgekit.stats import (
    BootstrapCI,
    bootstrap_ci,
    cohen_kappa,
    krippendorff_alpha,
    percent_agreement,
)

__version__ = "0.2.0"

__all__ = [
    "AgreementEstimate",
    "AnthropicProvider",
    "BootstrapCI",
    "BudgetExceededError",
    "CalibrationError",
    "CalibrationReport",
    "Case",
    "CaseRecord",
    "Dataset",
    "DatasetError",
    "JudgeConfig",
    "JudgeConfigRecord",
    "JudgeError",
    "JudgeParams",
    "JudgePricing",
    "JudgeRunArtifact",
    "JudgeRunManifest",
    "JudgeTotals",
    "JudgeVerdict",
    "JudgekitError",
    "KappaEstimate",
    "OpenAICompatibleProvider",
    "OutputRecord",
    "Provider",
    "ProviderError",
    "ProviderRequest",
    "ProviderResponse",
    "RaterRatings",
    "RaterSummary",
    "RatingRecord",
    "RunArtifact",
    "RunError",
    "RunManifest",
    "RunResult",
    "RunSummary",
    "Scorer",
    "ScoringError",
    "SliceAgreement",
    "StatsError",
    "UnknownScorerError",
    "available_scorers",
    "bootstrap_ci",
    "cohen_kappa",
    "execute_calibration",
    "execute_judge",
    "execute_run",
    "get_provider",
    "get_scorer",
    "krippendorff_alpha",
    "load_dataset",
    "load_judge_config",
    "load_outputs",
    "load_rater",
    "load_ratings",
    "percent_agreement",
    "register",
    "write_artifact",
    "write_judge_artifact",
    "write_report",
]
